# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitCircle <- function(x, y) {
    .Call(`_LiTreeAnyDensity_fitCircle`, x, y)
}

rc_cpp <- function(data, n, k, t, d) {
    .Call(`_LiTreeAnyDensity_rc_cpp`, data, n, k, t, d)
}

rmc_cpp <- function(data, n, k, t, d, max_circles) {
    .Call(`_LiTreeAnyDensity_rmc_cpp`, data, n, k, t, d, max_circles)
}

