# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitCircle <- function(x, y) {
    .Call(`_LiTreeAnyDensity_fitCircle`, x, y)
}

rc_cpp <- function(data, n, k, t, d) {
    .Call(`_LiTreeAnyDensity_rc_cpp`, data, n, k, t, d)
}

rmc_cpp <- function(data, n, k, t, d, max_circles) {
    .Call(`_LiTreeAnyDensity_rmc_cpp`, data, n, k, t, d, max_circles)
}

overlay_func_cpp <- function(data, number_layers, values_x, values_y, j1) {
    .Call(`_LiTreeAnyDensity_overlay_func_cpp`, data, number_layers, values_x, values_y, j1)
}

vectorized_custom_fun_bis <- function(x, y, valx, valy) {
    .Call(`_LiTreeAnyDensity_vectorized_custom_fun_bis`, x, y, valx, valy)
}

overlay_func <- function(data, number_layers, values_x, values_y, j1) {
    .Call(`_LiTreeAnyDensity_overlay_func`, data, number_layers, values_x, values_y, j1)
}

